name: Release

permissions:
  contents: write
  actions: write

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
      - test/ci

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: 生成changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_SELF_TOKEN}}
